# Generated by Django 5.1.3 on 2024-12-19 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0003_buy_payment_method_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_app.user_details'),
        ),
    ]
