# Generated by Django 5.1.3 on 2025-01-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0005_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
